### ISSUE TITLE
Card UI does not look great

### ISSUE THREAD

**Issue by norman2837** [smolBlackCat/progress-tracker#13]
I suggest adding a background or outline
![photo_2024-04-28_19-20-50](https://github.com/smolBlackCat/progress-tracker/assets/165981599/81bb10c5-3279-4117-8d27-ad2a2aa815fc)
 to the Card so that the tasks are better distinguishable. 
I also offer the ability to change the background color.

**Comment by smolBlackCat** [comment]
Indeed, the cards are quite ugly. I'll work on making it look more like an actual card.

However, I'll leave the ability to change card's colour on a next major release, since new information will have to be computed by the core library

**Comment by smolBlackCat** [comment]
## Current Situation

I'm almost there. Progress cards now look a lot more like an actual card

![Screenshot from 2024-05-04 10-03-18](https://github.com/smolBlackCat/progress-tracker/assets/66385489/e0772084-6b71-4cf4-b3cc-4e4989a328b8)

What I have to ensure is that the right colour is set to the card. As you can see in the picture above, the card's colour is #3d3846. The problem is that the colour is constant, it won't change to an appropriate colour when the host system theme is set to `Light`

![image](https://github.com/smolBlackCat/progress-tracker/assets/66385489/5c9eb226-f58a-42bf-812c-1768ba5bbdd1)

## Solution
This only seems to be a problem of loading the right stylesheet. The appropriate solution is to create stylesheets for both light and dark modes, and get the application to load the correct one.

**Comment by smolBlackCat** [comment]
Latest commit now addresses this issue
